### ISSUE TITLE
Not long enough! error

### ISSUE THREAD

**Issue by mocollin** [echicken/dpc2#1]
I have this problem with new users, who do not yet have a [doorparty] password in their /sbbs/data/xxxx.ini file.  When they attempt to load Doorparty, It displays the "Please Wait...." message then repeats the error "Not Long Enough!" over and over forever.

If the user already has a password, Doorparty works ok.

I am using SBBS for Linux, Jan 26 2021 build, on Ubuntu Linux.
There is nothing in the doorparty-connector log, I don't believe it's getting to the point that it's opening the tunnel. 
Based on my debugging, the issue is occurring in the make_password_ function in doorparty.js. 

![unknown](https://user-images.githubusercontent.com/1699666/107106491-ce83a000-67e0-11eb-9a0f-4828bb03ed55.png)

/ halls of valhalla bbs / hovalbbs.com 2333

**Comment by echicken** [comment]
c884a6b
